package starter.stepdefinitions.api.category;

import starter.api.category.AddCategoryPageAPI;
import io.cucumber.java.en.When;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.And;
import net.serenitybdd.annotations.Steps;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Step Definitions for Categories API - Add Category functionality
 * Test Cases:
 * - API_Category_CreateCategory_001 (Success case)
 * - API_Category_EmptyCategoryNameValidation_002 (Empty name validation)
 */
public class AddCategorySteps {

    @Steps
    AddCategoryPageAPI addCategoryPageAPI;

    // Constants
    private static final String VALIDATION_FAILED_MESSAGE = "Validation failed";
    private static final String MANDATORY_ERROR = "Category name is mandatory";
    private static final String LENGTH_ERROR = "Category name must be between 3 and 10 characters";
    private static final String FIELD_NAME = "name";
    private static final String FIELD_ID = "id";
    private static final String FIELD_SUB_CATEGORIES = "subCategories";

    // ==================== STEP DEFINITIONS ====================

    /**
     * Test Step: Admin user creates a main category with specified name
     * 
     * @param categoryName The name of the category to create
     */
    @When("Admin user sends POST request to create main category with name {string}")
    public void adminUserCreatesMainCategoryWithName(String categoryName) {
        Map<String, Object> categoryBody = buildCategoryRequestBody(categoryName);
        logCategoryCreationRequest(categoryName, categoryBody);

        addCategoryPageAPI.createCategory(categoryBody);

        // Verify API call was successful
        assertNotNull(addCategoryPageAPI.getResponse(),
                "API response is null. Request may not have been sent successfully.");
    }

    /**
     * Test Step: Verify response status code is 201 Created
     */
    @Then("API should return {int} Created status for category")
    public void apiShouldReturnCreatedStatusForCategory(int expectedStatus) {
        verifyStatusCode(expectedStatus, "API_Category_CreateCategory_001");
    }

    /**
     * Test Step: Verify API returns 400 Bad Request status
     */
    @Then("API should return {int} Bad Request status")
    public void apiShouldReturnBadRequestStatus(int expectedStatus) {
        verifyStatusCode(expectedStatus, "API_Category_EmptyCategoryNameValidation_002");
    }

    /**
     * Test Step: Verify response body contains the expected category name
     * 
     * @param expectedCategoryName The expected category name from feature file
     */
    @And("Response body should contain category name {string}")
    public void responseBodyShouldContainCategoryName(String expectedCategoryName) {
        String responseBody = addCategoryPageAPI.getResponseBody();

        assertNotNull(responseBody, "Response body is null");
        assertFalse(responseBody.isEmpty(), "Response body is empty");

        // Use JSONPath for more robust assertion
        String actualCategoryName = addCategoryPageAPI.getJsonPathValue(FIELD_NAME);

        assertEquals(expectedCategoryName, actualCategoryName,
                String.format("Expected category name '%s' but got '%s'",
                        expectedCategoryName, actualCategoryName));

        System.out.println("✓ Category name '" + expectedCategoryName + "' verified successfully in response");
    }

    /**
     * Test Step: Verify response body contains auto-generated category ID and
     * subCategories field
     */
    @And("Response body should contain auto-generated category ID")
    public void responseBodyShouldContainAutoGeneratedCategoryId() {
        String responseBody = addCategoryPageAPI.getResponseBody();

        try {
            Integer categoryId = addCategoryPageAPI.getJsonPathValue(FIELD_ID);
            String categoryName = addCategoryPageAPI.getJsonPathValue(FIELD_NAME);

            assertNotNull(categoryId, "Category ID should not be null");
            assertTrue(categoryId > 0,
                    "Category ID should be a positive integer. Got: " + categoryId);

            // Verify subCategories field exists in JSON
            assertTrue(responseBody.contains("\"" + FIELD_SUB_CATEGORIES + "\""),
                    "Response should contain '" + FIELD_SUB_CATEGORIES + "' field");

            logCategoryCreationSuccess(categoryId, categoryName);

        } catch (Exception e) {
            fail("Failed to extract main category details from response: " + e.getMessage()
                    + "\nResponse: " + responseBody);
        }
    }

    /**
     * Test Step: Verify main category is persisted in the system
     */
    @And("Main category should be created successfully in the system")
    public void mainCategoryShouldBeCreatedSuccessfullyInSystem() {
        String responseBody = addCategoryPageAPI.getResponseBody();

        try {
            Integer categoryId = addCategoryPageAPI.getJsonPathValue(FIELD_ID);

            assertNotNull(categoryId, "Category ID should not be null");
            assertTrue(categoryId > 0,
                    "Category ID should be a positive integer indicating successful persistence. Got: " + categoryId);

            System.out.println("✓ Category successfully persisted in system with ID: " + categoryId);
            System.out.println("✓ Test Case API_Category_CreateCategory_001 - PASSED");

        } catch (Exception e) {
            fail("Failed to verify category persistence in system. Response: " + responseBody
                    + "\nError: " + e.getMessage());
        }
    }

    /**
     * Test Step: Verify response contains validation error message (with parameter)
     */
    @Then("Response body should contain validation error message {string}")
    public void responseBodyShouldContainValidationErrorMessage(String expectedMessage) {
        String responseBody = addCategoryPageAPI.getResponseBody().toLowerCase();
        String messageToCheck = expectedMessage.toLowerCase();

        assertTrue(responseBody.contains(messageToCheck) || responseBody.contains("category name"),
                "Response should contain validation error message. Expected: '" + expectedMessage +
                        "'. Actual response: " + addCategoryPageAPI.getResponseBody());
    }

    /**
     * Test Step: Verify response contains validation error message (without
     * parameter)
     * Accepts multiple possible error messages for empty name validation
     */
    @And("Response body should contain validation error message")
    public void responseBodyShouldContainValidationErrorMessage() {
        String responseBody = addCategoryPageAPI.getResponseBody();

        assertNotNull(responseBody, "Response body should not be null");

        // Verify overall error structure
        String message = addCategoryPageAPI.getJsonPathValue("message");
        assertNotNull(message, "Error message should not be null");
        assertEquals(VALIDATION_FAILED_MESSAGE, message,
                "Expected '" + VALIDATION_FAILED_MESSAGE + "' message");

        // Verify details object exists
        Object details = addCategoryPageAPI.getJsonPathValue("details");
        assertNotNull(details, "Error details should not be null");

        // Extract the validation error for 'name' field
        String nameError = addCategoryPageAPI.getJsonPathValue("details." + FIELD_NAME);
        assertNotNull(nameError, "Validation error for 'name' field should exist");

        // Accept either validation message as both are valid for empty string
        boolean isValidError = nameError.equals(MANDATORY_ERROR) ||
                nameError.equals(LENGTH_ERROR);

        assertTrue(isValidError,
                buildValidationErrorMessage(nameError));

        logValidationErrorVerification(message, nameError);
    }

    /**
     * Test Step: Verify response contains error type BAD_REQUEST
     */
    @And("Response body should contain error type {string}")
    public void responseBodyShouldContainErrorType(String expectedErrorType) {
        String actualErrorType = addCategoryPageAPI.getJsonPathValue("error");

        assertNotNull(actualErrorType, "Error type should not be null");
        assertEquals(expectedErrorType, actualErrorType,
                String.format("Expected error type '%s' but got '%s'",
                        expectedErrorType, actualErrorType));

        System.out.println("✓ Error type verified: " + actualErrorType);
    }

    /**
     * Test Step: Verify category was not created in the system
     */
    @And("Category should not be created in the system")
    public void categoryShouldNotBeCreatedInSystem() {
        String responseBody = addCategoryPageAPI.getResponseBody();

        // Verify no ID field exists (category not created)
        assertFalse(responseBody.contains("\"" + FIELD_ID + "\""),
                "Response should not contain 'id' field for validation errors");

        // Verify error structure exists
        assertTrue(responseBody.contains("\"error\""),
                "Response should contain error information");
        assertTrue(responseBody.contains("\"details\""),
                "Response should contain validation details");
        assertTrue(responseBody.contains("\"status\""),
                "Response should contain status code");

        System.out.println("✓ Category was not created (validation prevented creation)");
        System.out.println("✓ Test Case API_Category_EmptyCategoryNameValidation_002 - PASSED");
    }

    // ==================== HELPER METHODS ====================

    /**
     * Builds the request body for creating a category
     * 
     * @param categoryName The name of the category
     * @return Map containing the category request body
     */
    private Map<String, Object> buildCategoryRequestBody(String categoryName) {
        Map<String, Object> categoryBody = new HashMap<>();
        categoryBody.put(FIELD_NAME, categoryName);
        return categoryBody;
    }

    /**
     * Logs the category creation request details
     */
    private void logCategoryCreationRequest(String categoryName, Map<String, Object> categoryBody) {
        System.out.println("═══════════════════════════════════════════════════════");
        System.out.println("Creating MAIN category with name: " + categoryName);
        System.out.println("Request Body: " + categoryBody);
        System.out.println("═══════════════════════════════════════════════════════");
    }

    /**
     * Verifies the status code and logs the details
     */
    private void verifyStatusCode(int expectedStatus, String testCaseId) {
        int actualStatus = addCategoryPageAPI.getStatusCode();
        String responseBody = addCategoryPageAPI.getResponseBody();

        System.out.println("═══════════════════════════════════════════════════════");
        System.out.println("API Test: " + testCaseId);
        System.out.println("Endpoint: POST /api/categories");
        System.out.println("Expected Status: " + expectedStatus);
        System.out.println("Actual Status: " + actualStatus);
        System.out.println("Response Body: " + responseBody);
        System.out.println("═══════════════════════════════════════════════════════");

        assertEquals(expectedStatus, actualStatus,
                String.format("Expected status code %d, but got: %d\nResponse: %s",
                        expectedStatus, actualStatus, responseBody));
    }

    /**
     * Logs successful category creation
     */
    private void logCategoryCreationSuccess(Integer categoryId, String categoryName) {
        System.out.println("✓ Main category created successfully:");
        System.out.println("  - Category ID: " + categoryId + " (auto-generated)");
        System.out.println("  - Category Name: " + categoryName);
        System.out.println("  - SubCategories field: present (value: null)");
        System.out.println("✓ All main category details verified successfully");
    }

    /**
     * Logs validation error verification
     */
    private void logValidationErrorVerification(String message, String nameError) {
        System.out.println("✓ Validation error structure verified:");
        System.out.println("  - Message: " + message);
        System.out.println("  - Field: " + FIELD_NAME);
        System.out.println("  - Error: " + nameError);
    }

    /**
     * Builds validation error message for assertions
     */
    private String buildValidationErrorMessage(String actualError) {
        return String.format("Expected validation error for empty category name.\n" +
                "Expected one of:\n" +
                "  - '%s'\n" +
                "  - '%s'\n" +
                "But got: '%s'", MANDATORY_ERROR, LENGTH_ERROR, actualError);
    }
}