package starter.stepdefinitions.api.category;

import starter.api.category.AddEditCategoriesPageAPI;
import io.cucumber.java.en.When;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.And;
import net.serenitybdd.annotations.Steps;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

public class AddCategorySteps {

    @Steps
    AddEditCategoriesPageAPI addEditCategoriesPageAPI;

    // Constants
    private static final String FIELD_NAME = "name";
    private static final String FIELD_ID = "id";
    private static final String FIELD_SUB_CATEGORIES = "subCategories";

    // Create category steps

    @When("Admin user sends POST request to create main category with name {string}")
    public void adminUserCreatesMainCategoryWithName(String categoryName) {
        Map<String, Object> categoryBody = buildCategoryRequestBody(categoryName);
        logCategoryCreationRequest(categoryName, categoryBody);

        addEditCategoriesPageAPI.createCategory(categoryBody);

        // Verify API call was successful
        assertNotNull(addEditCategoriesPageAPI.getResponse(),
                "API response is null. Request may not have been sent successfully.");
    }

    // Verify response status code is 201 Created
    @Then("API should return {int} Created status for category")
    public void apiShouldReturnCreatedStatusForCategory(int expectedStatus) {
        verifyStatusCode(expectedStatus, "API_Category_CreateCategory_001");
    }

    // Test Step: Verify API returns 400 Bad Request status
    @And("Response body should contain category name {string}")
    public void responseBodyShouldContainCategoryName(String expectedCategoryName) {
        String responseBody = addEditCategoriesPageAPI.getResponseBody();

        assertNotNull(responseBody, "Response body is null");
        assertFalse(responseBody.isEmpty(), "Response body is empty");

        // Use JSONPath for more robust assertion
        String actualCategoryName = addEditCategoriesPageAPI.getJsonPathValue(FIELD_NAME);

        assertEquals(expectedCategoryName, actualCategoryName,
                String.format("Expected category name '%s' but got '%s'",
                        expectedCategoryName, actualCategoryName));

        System.out.println("✓ Category name '" + expectedCategoryName + "' verified successfully in response");
    }

    // Verify response contains auto-generated category ID and subCategories field
    @And("Response body should contain auto-generated category ID")
    public void responseBodyShouldContainAutoGeneratedCategoryId() {
        String responseBody = addEditCategoriesPageAPI.getResponseBody();

        try {
            Integer categoryId = addEditCategoriesPageAPI.getJsonPathValue(FIELD_ID);
            String categoryName = addEditCategoriesPageAPI.getJsonPathValue(FIELD_NAME);

            assertNotNull(categoryId, "Category ID should not be null");
            assertTrue(categoryId > 0,
                    "Category ID should be a positive integer. Got: " + categoryId);

            // Verify subCategories field exists in JSON
            assertTrue(responseBody.contains("\"" + FIELD_SUB_CATEGORIES + "\""),
                    "Response should contain '" + FIELD_SUB_CATEGORIES + "' field");

            logCategoryCreationSuccess(categoryId, categoryName);

        } catch (Exception e) {
            fail("Failed to extract main category details from response: " + e.getMessage()
                    + "\nResponse: " + responseBody);
        }
    }

    // Test Step: Verify main category is persisted in the system
    @And("Main category should be created successfully in the system")
    public void mainCategoryShouldBeCreatedSuccessfullyInSystem() {
        String responseBody = addEditCategoriesPageAPI.getResponseBody();

        try {
            Integer categoryId = addEditCategoriesPageAPI.getJsonPathValue(FIELD_ID);

            assertNotNull(categoryId, "Category ID should not be null");
            assertTrue(categoryId > 0,
                    "Category ID should be a positive integer indicating successful persistence. Got: " + categoryId);

            System.out.println("✓ Category successfully persisted in system with ID: " + categoryId);
            System.out.println("✓ Test Case API_Category_CreateCategory_001 - PASSED");

        } catch (Exception e) {
            fail("Failed to verify category persistence in system. Response: " + responseBody
                    + "\nError: " + e.getMessage());
        }
    }

    // Test Step: Verify category was not created in the system
    @And("Category should not be created in the system")
    public void categoryShouldNotBeCreatedInSystem() {
        String responseBody = addEditCategoriesPageAPI.getResponseBody();

        // Verify category not created
        assertFalse(responseBody.contains("\"" + FIELD_ID + "\""),
                "Response should not contain 'id' field for validation errors");

        // Verify error structure exists
        assertTrue(responseBody.contains("\"error\""),
                "Response should contain error information");
        assertTrue(responseBody.contains("\"details\""),
                "Response should contain validation details");
        assertTrue(responseBody.contains("\"status\""),
                "Response should contain status code");

        System.out.println("Category was not created");
        System.out.println("Validation test - PASSED");
    }

    // helper methods

    // Builds the request body for creating a category
    private Map<String, Object> buildCategoryRequestBody(String categoryName) {
        Map<String, Object> categoryBody = new HashMap<>();
        categoryBody.put(FIELD_NAME, categoryName);
        return categoryBody;
    }

    // Logs the category creation request details
    private void logCategoryCreationRequest(String categoryName, Map<String, Object> categoryBody) {
        System.out.println("Creating MAIN category with name: '" + categoryName + "'");
        System.out.println("Name Length: " + categoryName.length() + " characters");
        System.out.println("Request Body: " + categoryBody);
    }

    // Verifies the status code and logs the details
    private void verifyStatusCode(int expectedStatus, String testCaseId) {
        int actualStatus = addEditCategoriesPageAPI.getStatusCode();
        String responseBody = addEditCategoriesPageAPI.getResponseBody();

        System.out.println("API Test: " + testCaseId);
        System.out.println("Endpoint: POST /api/categories");
        System.out.println("Expected Status: " + expectedStatus);
        System.out.println("Actual Status: " + actualStatus);
        System.out.println("Response Body: " + responseBody);

        assertEquals(expectedStatus, actualStatus,
                String.format("Expected status code %d, but got: %d\nResponse: %s",
                        expectedStatus, actualStatus, responseBody));
    }

    // Logs successful category creation
    private void logCategoryCreationSuccess(Integer categoryId, String categoryName) {
        System.out.println("Main category created successfully:");
        System.out.println("Category ID: " + categoryId);
        System.out.println("Category Name: " + categoryName);
        System.out.println("SubCategories field");
        System.out.println("All main category details verified successfully");
    }
}